import Head from "next/head";
import styles from "../styles/Home.module.css";
import "fontsource-roboto";
import {
  createViewState,
  JBrowseLinearGenomeView,
} from "@jbrowse/react-linear-genome-view";

export default function Home() {
  const state = createViewState({
    assembly: {
      name: "ASM15095v2",
      sequence: {
        type: "ReferenceSequenceTrack",
        trackId: "ASM15095v2-ReferenceSequenceTrack",
        adapter: {
          type: "BgzipFastaAdapter",
          fastaLocation: {
            uri: "/Phaeodactylum_tricornutum.ASM15095v2.dna.toplevel.fa.gz",
          },
          faiLocation: {
            uri: "/Phaeodactylum_tricornutum.ASM15095v2.dna.toplevel.fa.gz.fai",
          },
          gziLocation: {
            uri: "/Phaeodactylum_tricornutum.ASM15095v2.dna.toplevel.fa.gz.gzi",
          },
        },
      },
      refNameAliases: {
        adapter: {
          type: "RefNameAliasAdapter",
          location: { uri: "/ASM15095v2_aliases.txt" },
        },
      },
    },
    tracks: [
      {
        type: "FeatureTrack",
        trackId: "ASM15095v2-genes",
        name: "Phatr3 gene models (Ensembl)",
        category: ["  Genes"],
        assemblyNames: ["ASM15095v2"],
        adapter: {
          type: "Gff3TabixAdapter",
          gffGzLocation: {
            uri: "/phatr3_gene_models_with_href.gff3.gz",
          },
          index: {
            location: {
              uri: "/phatr3_gene_models_with_href.gff3.gz.tbi",
            },
            indexType: "TBI",
          },
        },
        renderer: {
          type: "SvgFeatureRenderer",
        },
      },
    ],
  });

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <JBrowseLinearGenomeView viewState={state} />
    </div>
  );
}
